name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Priyanshuthapliyal2005
          outputs: dist/snake.svg

      - name: Upload Snake Image
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Push Snake to Output Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          path: dist/snake.svg
